### ISSUE TITLE
Issue: usage column is sorted as text, not as numbers

### ISSUE THREAD

**Issue by skfd** [AmraouiH/Entity-Field-Analyser#1]
Here is how it looks!
![image](https://github.com/AmraouiH/Entity-Field-Analyser/assets/159640/f0cb8e50-8269-435d-b215-161cfa0b582f)

**Comment by AmraouiH** [comment]
Hello @skfd, 
Glad to hear from you.
The issue is fixed on version 2.0.0.5
Thank you for your report.
Hamza
